const selectors = {
	processList: "#processes",
	operationsList: "#operations",
	handlersList: "#handlers",
	listWrap: ".list-wrap",
	list: ".list",
	listItem: ".list-item",
	btnEdit: ".edit",
	btnDelete: ".delete",
	btnSave: ".save-element",
	btnAdd: ".btn-add",
	btnCloseModal: ".close-modal",
	modal: ".modal",
	modalTitle: ".modal",
	modalContent: ".modal-content",
};